services:
  mongodb-to-postgresql-migration:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile  # Use the Dockerfile named "Dockerfile"
    env_file:
      - ./cred/.env  # Path to the .env file
    volumes:
      - app/pg-to-mongo/logs:/app/logs  # Mount logs
      - app/pg-to-mongo/cred:/app/cred  # env and other credentials files
      - app/pg-to-mongo/config:/app/config # configiguration file
    #environment:
    #  - GOOGLE_APPLICATION_CREDENTIALS=/app/cred/service-account-key.json  # Add environment variables if needed
